![http://www.numpy.org/_static/numpy_logo.png](http://www.numpy.org/_static/numpy_logo.png)

# Introduction à [numpy](http://www.numpy.org/)

In [1]:
import numpy as np

## Structure de donnée de base : le `ndarray`

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
type(a)

numpy.ndarray

### Propriétés des arrays

In [4]:
a.size  # nombre d'éléments

7

In [5]:
a.ndim  # nombre de dimension

1

In [6]:
a.shape  # taille de chaque dimension

(7,)

In [7]:
a.dtype  # type de l'object

dtype('int64')

### Array à plusieurs dimensions

In [8]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print("type d'objet: {0}\n"
      "size: {o.size}\n"
      "ndim: {o.ndim}\n"
      "shape: {o.shape}\n"
      "dtype: {o.dtype}"
      .format(type(b), o=b))

type d'objet: <class 'numpy.ndarray'>
size: 8
ndim: 2
shape: (2, 4)
dtype: int64


### Méthodes des arrays

In [10]:
a.min(), a.max(), a.mean(), a.sum(), a.argmin(), a.argmax()

(1, 7, 4.0, 28, 0, 6)

In [11]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
b.sum()

36

In [13]:
b.sum(axis=0)

array([ 6,  8, 10, 12])

In [14]:
b.sum(axis=1)

array([10, 26])

In [15]:
c = np.array([3, 7, 5, 1])
print(c)
c.sort()
print(c)

[3 7 5 1]
[1 3 5 7]


In [16]:
c = np.array([3, 7, 5, 1])
print(c)
s = c.argsort()  # retourne les indexes des éléments organisés par ordre croissant
print(s)

[3 7 5 1]
[3 0 2 1]


In [17]:
d = np.array([1, 2, 3, 4])
d[c.argsort()]  # réorganiser 'd' en fonction de 'c'

array([4, 1, 3, 2])

## Opérations avec les arrays

In [18]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
a - 5

array([-4, -3, -2, -1,  0,  1,  2])

In [20]:
a * np.pi / 3

array([ 1.04719755,  2.0943951 ,  3.14159265,  4.1887902 ,  5.23598776,
        6.28318531,  7.33038286])

In [21]:
a**np.e, np.e**a

(array([   1.        ,    6.58088599,   19.81299075,   43.30806043,
          79.43235917,  130.38703324,  198.25066166]),
 array([    2.71828183,     7.3890561 ,    20.08553692,    54.59815003,
          148.4131591 ,   403.42879349,  1096.63315843]))

In [22]:
a * a  # elements par élément

array([ 1,  4,  9, 16, 25, 36, 49])

In [23]:
a @ a  # équivalent à np.dot(a, a) en python 2

140

In [24]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
a < 4

array([ True,  True,  True, False, False, False, False], dtype=bool)

In [26]:
a == 4

array([False, False, False,  True, False, False, False], dtype=bool)

In [27]:
(a > 2) & (a < 4)  # bitwise AND

array([False, False,  True, False, False, False, False], dtype=bool)

In [79]:
a < np.array([2, 3, 5, 2, 1, 5, 7])

array([ True,  True,  True, False, False, False, False], dtype=bool)

In [30]:
np.sum(a > 2)  # True == 1 et False == 0

5

## Indexing et slicing de base

Indexing : élement(s) / Slicing : sous-tableau 

In [31]:
a[0]  # indexing commencent à 0

1

In [32]:
a[-1]  # -1 fais référence au derier élément

7

In [33]:
a[2:6:3]  # comme en python : [start:end:step]

array([3, 6])

In [34]:
a[::-1]  # pour inverser un array

array([7, 6, 5, 4, 3, 2, 1])

In [35]:
print(b)
print(b[::-1])  # inverse selon l'axe 0

[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]]


### Indexing et slicing à plusieurs dimensions

In [36]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
b[0, 2], b[0, 1:4]

(3, array([2, 3, 4]))

In [39]:
b[:, 1:4]  # le `:` selectionne l'axe entier

array([[2, 3, 4],
       [6, 7, 8]])

In [40]:
b[:, 2:5:2]

array([[3],
       [7]])

In [41]:
b[::-1, ::-1]  # inverse le sdeux axes

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

### Indexing avancé

In [42]:
d = np.array([4, 3, 2, 5, 4, 5])

In [43]:
mask = np.array([True, False, False, True, False, False])
mask

array([ True, False, False,  True, False, False], dtype=bool)

In [44]:
d[mask]

array([4, 5])

In [45]:
d[[1, 3, 0]]

array([3, 5, 4])

## Vues et copies

In [81]:
n = np.arange(10)  #  = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
o = n         # `o` va directement pointer sur `n`
o[2] = 99
n             # modifier `o` va aussi modifier `n`

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [48]:
p = n[5]      # l'accès à un unique élément retourne une copie
p             # (pas un pointeur)

5

In [49]:
p = 9999
o             # modifier p ne modifiera donc pas 'o'

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [50]:
q = o[2:4]    # une 'slice' retourne une vue (en mémoire) (un pointeur)
q

array([99,  3])

In [51]:
q[0] = -5
o             # 'o' sera donc affecté par une modification sur 'q'

array([ 0,  1, -5,  3,  4,  5,  6,  7,  8,  9])

In [52]:
o[3:6] = [101, 102, 103]   # il est aussi possible de modifier plusieurs éléments meme temps
o

array([  0,   1,  -5, 101, 102, 103,   6,   7,   8,   9])

## Functions utiles pour créer des arrays

In [53]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
np.ones(12)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [56]:
np.zeros((2, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [57]:
np.empty(15)

array([  6.92635380e-310,   1.34830357e-316,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         3.16202013e-322,   3.95252517e-322,   1.21568607e-316,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000])

In [58]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [59]:
np.linspace(1, 3, 10)   # np.meshgrid pour du 2d ou plus

array([ 1.        ,  1.22222222,  1.44444444,  1.66666667,  1.88888889,
        2.11111111,  2.33333333,  2.55555556,  2.77777778,  3.        ])

In [60]:
np.ones_like(b)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
np.ones(10, dtype='i2')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

### Nombres aléatoires

In [62]:
# donne la liste des distributions possibles
np.random?

In [63]:
np.random.randint(1, 10, (2, 20))  # (start, end(+1), shape)

array([[2, 1, 7, 4, 2, 6, 6, 2, 6, 5, 4, 2, 7, 5, 8, 6, 6, 6, 4, 6],
       [7, 3, 9, 9, 4, 7, 3, 7, 4, 9, 8, 3, 4, 4, 6, 7, 2, 3, 5, 3]])

In [64]:
np.random.random((3, 5))  # 

array([[ 0.14279367,  0.36824996,  0.88319791,  0.4674143 ,  0.7446856 ],
       [ 0.9026069 ,  0.4302789 ,  0.49927715,  0.80587466,  0.1397677 ],
       [ 0.50708932,  0.51078927,  0.25596616,  0.14917221,  0.57735479]])

## Manipuler des arrays

In [65]:
# si les shapes se correspondent, les opérations sont faites 
# élément par élément
g = np.array([1, 2, 3, 4])
h = np.array([5, 6, 7, 8])
g * h

array([ 5, 12, 21, 32])

In [66]:
g * 23

array([23, 46, 69, 92])

### Règles générales du broadcasting

- Les dimensions de deux tableaux sont compatibles si, pour chaque axe, leurs tailles sont soit égales soit égales à 1
  - (3, 2) et (1, 2) -> broadcastable
  - (3, 2) et (2, 1) -> non broadcastable
- La taille d'un array braodcasté est la taille maximum le long de chaque axe des tableaux d'entrées
  - (3, 2, 1) × (1, 2, 4) → (3, 2, 4)
- Si le rang d'un des tableaux (ndim) est inférieur au rang de l'autre tableau, son format (shape) est alors précédé d’autant de 1 nécessaire pour atteindre le même rang
  - (3, 2, 1) × (4,) = (3, 2, 1) × (1, 1, 4) → (3, 2, 4).
- Si les shapes sont incompatibles, une `ValueError` est levée

### Operations sur des array de shapes différentes

```
A      (4d array): 3 x 1 x 2 x 1
B      (3d array):     5 x 1 x 6 (== 1 x 5 x 1 x 6)
Donne  (4d array): 3 x 5 x 2 x 6
```

In [67]:
i = np.arange(20).reshape(4, 5)
i

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
print("type d'objet: {0}\n"
      "size: {o.size}\n"
      "ndim: {o.ndim}\n"
      "shape: {o.shape}\n"
      "dtype: {o.dtype}"
      .format(type(i), o=i))

type d'objet: <class 'numpy.ndarray'>
size: 20
ndim: 2
shape: (4, 5)
dtype: int64


In [69]:
i * np.array([0, 1, 2, 4, 5])

array([[ 0,  1,  4, 12, 20],
       [ 0,  6, 14, 32, 45],
       [ 0, 11, 24, 52, 70],
       [ 0, 16, 34, 72, 95]])

In [70]:
j = np.array([0, 10, 20, 30])
k = np.array([7, 8, 9])

In [71]:
j+k

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [82]:
j[:, np.newaxis]  # inser un nouvel axe -> 2D

array([[ 0],
       [10],
       [20],
       [30]])

In [73]:
j[:, np.newaxis] + k

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39]])

In [85]:
print(np.shape(j[:, np.newaxis]))
print(np.shape(k))
print(np.shape(j[:, np.newaxis] + k))

(4, 1)
(3,)
(4, 3)


## Les fonctions universelles (`ufunc`)

- "Wrappeur" vectorisé d'une fonction avec un nombre fixe d'entrée/sortie scalaire
- p.e : `add`, `log20`, `sin`, `cos`, etc.
- Toutes ces fonctions sont des sous-classes de `np.ufunc`

In [74]:
def test(x):
    return 1 if x > 5 else 0
print(test(1), test(10))

0 1


In [75]:
utest = np.frompyfunc(test, 1, 1)
print(utest(1), utest(10))

0 1


In [76]:
test([1, 10])

TypeError: '>' not supported between instances of 'list' and 'int'

In [77]:
utest([1, 10])

array([0, 1], dtype=object)

In [78]:
type(np.cos), type(utest)

(numpy.ufunc, numpy.ufunc)

## Et bien plus encore... 

Numpy a de très nombreuses fonctionnalités supplementaires qu'il serait impossible de décrire en un temps si cours. En voici quelques exemples.

- stacking avec `np.hstack`, `np.vstack`, `np.dstack`
- modification de format (shape) d'array avec `reshape`, `ravel`, `transpose`, `resize`
- tableau évolué de différents types avec `np.dtype` et `np.array`
- etc

Pour un listing complet et des exemples, voir le [manuel de référence](https://docs.scipy.org/doc/numpy/reference/) de numpy.