# Exercices de base sur NumPy

In [66]:
import numpy as np

[4 3 2 1 0]
None [0 1 2 3 4]


## Exercice 1

1. Créer une matrice 4 x 4 avec 4 sur sa diagonale. 
2. Remplacer les valeurs des 4 coins de cette matrice par 1
3. Remplacer les valeurs de la colonne d'indice 2 par des 3
4. Faire la somme :
  - de la première ligne de la matrice
  - de la troisième colonne
  - selon le premier axe (axe 0)
  - du contenu complet de la matrice
5. Faire la moyenne du contenue de la matrice
6. Transposer la matrice obtenue en 3.         
7. Comparer 2 méthodes pour créer la matrice du 1 avec 500 éléments. (utiliser `%%timeit` au début de la cellule)

In [2]:
# 1. Créer une matrice 4 x 4 avec 4 sur sa diagonale. 
m = np.eye(4) * 4
print(m)

[[ 4.  0.  0.  0.]
 [ 0.  4.  0.  0.]
 [ 0.  0.  4.  0.]
 [ 0.  0.  0.  4.]]


In [3]:
# 2. Remplacer les valeurs des 4 coins de cette matrice par 1
m[0, [0, -1]] = m[-1, (0, -1)] = 1
print(m)

[[ 1.  0.  0.  1.]
 [ 0.  4.  0.  0.]
 [ 0.  0.  4.  0.]
 [ 1.  0.  0.  1.]]


In [4]:
# 3. Remplacer les valeurs de la colonne d'indice 2 par des 3
m[:, 2] = 3
print(m)

[[ 1.  0.  3.  1.]
 [ 0.  4.  3.  0.]
 [ 0.  0.  3.  0.]
 [ 1.  0.  3.  1.]]


In [5]:
# 4. Sommes
print(m[0].sum(), m[:, 2].sum(), m.sum(axis=0), m.sum())

5.0 12.0 [  2.   4.  12.   2.] 20.0


In [6]:
# 5. Moyenne
print(m.mean())

1.25


In [70]:
# 6. Transposer la matrice obtenue en 3.
print(m.T)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [77]:
# 7. Comparaison avec timeit
# np.diag(np.ones(4) * 4))
np.linalg?

In [71]:
%timeit np.diag(np.ones(500) * 4)

106 µs ± 222 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%%timeit
np.eye(500) * 4

215 µs ± 9.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Exercice 2

1. Créer un array de 1000 valeurs aléatoires de distribution gaussienne.
2. En calculer la moyenne et la déviation standard
3. Décaler le centre de la gaussienne pour que sa moyenne soit égale à 3 (vérifier la moyenne et la déviation standard)
4. Normaliser la distribution pour que l'intégrale (la somme) soit égale à 1
5. Remplacer sa plus petite valeur par 0

In [87]:
# 1. Créer un array de 1000 valeurs aléatoires de distribution gaussienne.
a = np.random.randn(1000)

In [12]:
# 2. En calculer la moyenne et la déviation standard
a.mean(), a.std()

(-0.019651049774479592, 0.96803108122154347)

In [13]:
# 3. Décaler le centre de la gaussienne pour que sa moyenne soit égale à 3
a += 3  # a = a + 3
a.mean(), a.std()

(2.9803489502255207, 0.96803108122154347)

In [14]:
# 4. Normaliser la distribution pour que l'intégrale (la somme) soit égale à 1
a /= a.sum()
a.sum()

0.99999999999999989

In [15]:
# 5. Remplacer sa plus petite valeur par 0
a[a.argmin()] = 0
a[a.argmin()]

0.0

## Exercice 3

1. Créer un array contenant les nombre suivants
    
        [[ 1.  2.  3.  4.  5.]
         [ 1.  2.  3.  4.  5.]
         [ 1.  2.  3.  4.  5.]
         [ 1.  2.  3.  4.  5.]
         [ 1.  2.  3.  4.  5.]]
    
2. Le transformer en

         [1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,
          4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.]
        
3. Le mettre au carré, et sommer

In [89]:
# 1. Créer un array
a = np.zeros((5, 5)) + np.arange(1, 6)
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]]


In [93]:
# 2. Le "dérouler"
a.flatten()   # a.ravel()

array([ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,
        4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.])

In [98]:
a.reshape(25)

array([ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,
        4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.])

In [19]:
a.ravel() ** 2

array([  1.,   4.,   9.,  16.,  25.,   1.,   4.,   9.,  16.,  25.,   1.,
         4.,   9.,  16.,  25.,   1.,   4.,   9.,  16.,  25.,   1.,   4.,
         9.,  16.,  25.])

In [20]:
# 3. Le mettre au carré, et sommer
(a.ravel() ** 2).sum()

275.0

## Exercice 4

Créer la matrice suivante

        0 0 0 0 1
        0 0 0 1 0
        0 0 1 0 0
        0 1 0 0 0 
        1 0 0 0 0

In [21]:
m = np.eye(5)
m

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
m[:, ::-1]

array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.]])

In [23]:
m[::-1, :]

array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.]])

## Exercice 5

Créer un damier de taille 8 x 8

    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0

In [24]:
damier = np.zeros((8, 8), dtype='i')
damier[::2, 1::2] = 1
damier[1::2, ::2] = 1
damier

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

## Exercice 6

1. Créer un array de 10 éléments équidistants les uns des autres, entre 0 et 10 exclus.
2. Dans cet array, trouver la valeur la plus proche de 8
3. Extraire la partie entière de chaque élément de cet array

In [25]:
# 1. Créer un array de 10 élément équidistant les uns des autres, entre 0 et 1 exclus.
a = np.linspace(0, 10, 11, endpoint=False)[1:]
print(a)

[ 0.90909091  1.81818182  2.72727273  3.63636364  4.54545455  5.45454545
  6.36363636  7.27272727  8.18181818  9.09090909]


In [26]:
a = np.linspace(0, 10, 12)[1:-1]
print(a)

[ 0.90909091  1.81818182  2.72727273  3.63636364  4.54545455  5.45454545
  6.36363636  7.27272727  8.18181818  9.09090909]


In [27]:
# 2. Dans cet array, trouver la valeur la plus proche de 8
a[np.abs(a - 8).argmin()]

8.1818181818181817

In [28]:
# 3. Extraire la partie entière de chaque élément de cet array
a.astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Alternatives et évaluation du temps

In [101]:
a = np.random.uniform(0, 20, 10000)

In [30]:
%timeit a.astype(int)

7.55 µs ± 320 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
%timeit np.floor(a)

30 µs ± 197 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [32]:
%timeit np.ceil(a) - 1

36 µs ± 230 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [102]:
%timeit np.trunc(a)
np.trunc(a)

42.5 µs ± 226 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


array([ 12.,  11.,   6., ...,   0.,   0.,  16.])

In [34]:
%timeit a -a%1

89.7 µs ± 82.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Exercice 7

1. Créer un array contenant les coordonnées 3D aléatoires (`n_dims=3`) de 4 points de l'espace (`n_points=4`), 
2. Écrire une fonction qui retourne les indices des points les plus proches dans ce même array, pour chaque points de cet array.
2. Comparer les performances de cette fonction à la fonction `NearestNeighbors` de `scikit-learn` (ci-dessous)

In [35]:
def nearset_neighbors_sklear(data):
    from sklearn.neighbors import NearestNeighbors
    nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(data)
    distances, indices = nbrs.kneighbors(data)
    return indices[:, 1]

In [36]:
n_points = 4
n_dims = 3

In [37]:
data = np.random.random((n_points, n_dims))
print(np.shape(data))
print(data)

(4, 3)
[[ 0.77947981  0.81483345  0.20041095]
 [ 0.95753907  0.53972189  0.78665739]
 [ 0.46145355  0.47296935  0.20150036]
 [ 0.56214908  0.18860238  0.55698831]]


In [38]:
def nearset_neighbors(data):
    n_points, n_dims = np.shape(data)
    distances = np.sum((data.reshape(n_points, 1, n_dims) - data)**2, 
                       axis=2)
    distances[np.diag_indices_from(distances)] = np.inf
    return np.argmin(distances, axis=1)

In [39]:
nearset_neighbors_sklear(data) == nearset_neighbors(data)

array([ True,  True,  True,  True], dtype=bool)

In [40]:
data_reshaped = data.reshape(n_points, 1, n_dims)
print(np.shape(data_reshaped))
print(data_reshaped)

(4, 1, 3)
[[[ 0.77947981  0.81483345  0.20041095]]

 [[ 0.95753907  0.53972189  0.78665739]]

 [[ 0.46145355  0.47296935  0.20150036]]

 [[ 0.56214908  0.18860238  0.55698831]]]


In [41]:
difference = data_reshaped - data
print(np.shape(difference))
print(difference)

(4, 4, 3)
[[[ 0.          0.          0.        ]
  [-0.17805926  0.27511156 -0.58624643]
  [ 0.31802626  0.3418641  -0.00108941]
  [ 0.21733073  0.62623107 -0.35657736]]

 [[ 0.17805926 -0.27511156  0.58624643]
  [ 0.          0.          0.        ]
  [ 0.49608552  0.06675254  0.58515702]
  [ 0.39538999  0.35111951  0.22966908]]

 [[-0.31802626 -0.3418641   0.00108941]
  [-0.49608552 -0.06675254 -0.58515702]
  [ 0.          0.          0.        ]
  [-0.10069553  0.28436697 -0.35548795]]

 [[-0.21733073 -0.62623107  0.35657736]
  [-0.39538999 -0.35111951 -0.22966908]
  [ 0.10069553 -0.28436697  0.35548795]
  [ 0.          0.          0.        ]]]


In [42]:
distances = np.sum(difference**2, axis=2)
print(np.shape(distances))
print(distances)

(4, 4)
[[ 0.          0.45107635  0.21801295  0.56654541]
 [ 0.45107635  0.          0.59296549  0.33236604]
 [ 0.21801295  0.59296549  0.          0.21737584]
 [ 0.56654541  0.33236604  0.21737584  0.        ]]


In [43]:
distances[np.diag_indices_from(distances)] = np.inf  # supprimer les distances des points à eux-même

In [44]:
np.argmin(distances, axis=1)

array([2, 3, 3, 2])

#### Comparaison des efficacités

In [45]:
def nearset_neighbors_sklear(data):
    from sklearn.neighbors import NearestNeighbors
    nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(data)
    distances, indices = nbrs.kneighbors(data)
    return indices[:, 1]

In [46]:
n_points = 100
n_dims = 3

In [47]:
data = np.random.random((n_points, n_dims))

In [48]:
%timeit nearset_neighbors_sklear(data)

389 µs ± 608 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [49]:
%timeit nearset_neighbors(data)

310 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [50]:
n_points = 10000
n_dims = 3

In [51]:
data = np.random.random((n_points, n_dims))

In [52]:
%timeit nearset_neighbors_sklear(data)

42.1 ms ± 52.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [53]:
%timeit nearset_neighbors(data)

3.38 s ± 4.53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
