# Exercices de base sur NumPy

In [1]:
import numpy as np

## Exercice 1

1. Créer une matrice 4 x 4 avec 4 sur sa diagonale. 
2. Remplacer les valeurs des 4 coins de cette matrice par 1
3. Remplacer les valeurs de la colonne d'indice 2 par des 3
4. Faire la somme :
  - de la première ligne de la matrice
  - de la troisième colonne
  - selon le premier axe (axe 0)
  - du contenu complet de la matrice
5. Faire la moyenne du contenue de la matrice
6. Comparer 2 méthodes pour créer la matrice du 1 avec 500 éléments. (utiliser `%%timeit` au début de la cellule)

In [35]:
# 1. Créer une matrice 4 x 4 avec 4 sur sa diagonale. 
m = np.eye(4) * 4
print(m)

[[ 4.  0.  0.  0.]
 [ 0.  4.  0.  0.]
 [ 0.  0.  4.  0.]
 [ 0.  0.  0.  4.]]


In [17]:
# 2. Remplacer les valeurs des 4 coins de cette matrice par 1
m[0, (0, -1)] = m[-1, (0, -1)] = 1
print(m)

[[ 1.  0.  0.  1.]
 [ 0.  4.  0.  0.]
 [ 0.  0.  4.  0.]
 [ 1.  0.  0.  1.]]


In [19]:
# 3. Remplacer les valeurs de la colonne d'indice 2 par des 3
m[:, 2] = 3
print(m)

[[ 1.  0.  3.  1.]
 [ 0.  4.  3.  0.]
 [ 0.  0.  3.  0.]
 [ 1.  0.  3.  1.]]


In [25]:
# 4. Sommes
print(m[0].sum(), m[:, 2].sum(), m.sum(axis=0), m.sum())

5.0 12.0 [  2.   4.  12.   2.] 20.0


In [28]:
# 5. Moyenne
print(m.mean())

1.25


In [32]:
# 6. Comparaison avec timeit
np.diag(np.ones(4) * 4)

array([[ 4.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  4.]])

In [33]:
%%timeit
np.diag(np.ones(500) * 4)

115 µs ± 5.31 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [36]:
%%timeit
np.eye(500) * 4

229 µs ± 18.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Exercice 2

1. Créer un array de 1000 valeurs aléatoires de distribution gaussienne.
2. En calculer la moyenne et la déviation standard
3. Décaler le centre de la gaussienne pour que sa moyenne soit égale à 3 (vérifier la moyenne et la déviation standard)
4. Normaliser la distribution pour que l'intégrale (la somme) soit égale à 1
5. Remplacer sa plus petite valeur par 0

In [47]:
# 1. Créer un array de 1000 valeurs aléatoires de distribution gaussienne.
a = np.random.randn(1000)

In [48]:
# 2. En calculer la moyenne et la déviation standard
a.mean(), a.std()

(0.019791677144457304, 1.0017398008021072)

In [49]:
# 3. Décaler le centre de la gaussienne pour que sa moyenne soit égale à 3
a += 3
a.mean(), a.std()

(3.0197916771444571, 1.0017398008021072)

In [56]:
# 4. Normaliser la distribution pour que l'intégrale (la somme) soit égale à 1
a /= a.sum()
a.sum()

1.0

In [60]:
# 5. Remplacer sa plus petite valeur par 0
a[a.argmin()] = 0
a[a.argmin()]

-4.6357544003563811e-05

## Exercice 3

1. Créer un array contenant les nombre suivants
    
        1 2 3 4 5
        1 2 3 4 5
        1 2 3 4 5
        1 2 3 4 5
        1 2 3 4 5
    
2. Le transformer en

         [1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,
          4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.]
        
3. Le mettre au carré, et sommer

In [290]:
# 1. Créer un array
a = np.ones((5, 5)) * np.arange(1, 6)
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]]


In [291]:
# 2. Le "dérouler"
a.ravel()

array([ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,
        4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.])

In [292]:
a.reshape(1, 25)

array([[ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,
         4.,  5.,  1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.]])

In [70]:
a.ravel() ** 2

array([  1.,   4.,   9.,  16.,  25.,   1.,   4.,   9.,  16.,  25.,   1.,
         4.,   9.,  16.,  25.,   1.,   4.,   9.,  16.,  25.,   1.,   4.,
         9.,  16.,  25.])

In [71]:
# 3. Le mettre au carré, et sommer
(a.ravel() ** 2).sum()

275.0

## Exercice 4

Créer un damier de taille 8 x 8

    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0

In [73]:
damier = np.zeros((8, 8), dtype='i')
damier[::2, 1::2] = 1
damier[1::2, ::2] = 1
damier

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

## Exercice 5

1. Créer un array de 10 éléments équidistants les uns des autres, entre 0 et 1 exclus.
2. Dans cet array, trouver la valeur la plus proche de 8
3. Extraire la partie entière de chaque élément de cet array

In [293]:
# 1. Créer un array de 10 élément équidistant les uns des autres, entre 0 et 1 exclus.
a = np.linspace(0, 10, 11, endpoint=False)[1:]
print(a)

[ 0.90909091  1.81818182  2.72727273  3.63636364  4.54545455  5.45454545
  6.36363636  7.27272727  8.18181818  9.09090909]


In [294]:
a = np.linspace(0, 10, 12)[1:-1]
print(a)

[ 0.90909091  1.81818182  2.72727273  3.63636364  4.54545455  5.45454545
  6.36363636  7.27272727  8.18181818  9.09090909]


In [295]:
# 2. Dans cet array, trouver la valeur la plus proche de 8
a[np.abs(a - 8).argmin()]

8.1818181818181817

In [296]:
# 3. Extraire la partie entière de chaque élément de cet array
a.astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Alternatives et évaluation du temps

In [132]:
a = np.random.uniform(0, 20, 10000)

In [133]:
%timeit a.astype(int)

6.19 µs ± 80.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [134]:
%timeit np.floor(a)

30.8 µs ± 480 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [135]:
%timeit np.ceil(a) - 1

37.4 µs ± 491 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [136]:
%timeit np.trunc(a)

43.3 µs ± 295 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [137]:
%timeit a -a%1

91 µs ± 205 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Exercice 6

1. Créer un array contenant les coordonnées 3D aléatoires (`n_dims=3`) de 4 points de l'espace (`n_points=4`), 
2. Écrire une fonction qui retourne les indices des points les plus proches dans ce même array, pour chaque points de cet array.
2. Comparer les performances de cette fonction à la fonction `NearestNeighbors` de `scikit-learn` (ci-dessous)

In [297]:
def nearset_neighbors_sklear(data):
    from sklearn.neighbors import NearestNeighbors
    nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(data)
    distances, indices = nbrs.kneighbors(data)
    return indices[:, 1]

In [300]:
n_points = 4
n_dims = 3

In [301]:
data = np.random.random((n_points, n_dims))
print(np.shape(data))
print(data)

(4, 3)
[[ 0.97197277  0.37302222  0.57591548]
 [ 0.00541308  0.96354502  0.45031983]
 [ 0.00920761  0.08480097  0.25496418]
 [ 0.43607756  0.46195006  0.72150335]]


In [247]:
def nearset_neighbors(data):
    n_points, n_dims = np.shape(data)
    distances = np.sum((data.reshape(n_points, 1, n_dims) - data)**2, axis=2)
    distances[np.diag_indices_from(distances)] = np.inf
    return np.argmin(distances, axis=1)

In [249]:
nearset_neighbors_sklear(data) == nearset_neighbors(data)

array([ True,  True,  True,  True], dtype=bool)

In [250]:
data_reshaped = data.reshape(n_points, 1, n_dims)
print(np.shape(data_reshaped))
print(data_reshaped)

(4, 1, 3)
[[[ 0.37584168  0.31295518  0.92184453]]

 [[ 0.32883427  0.6450784   0.06649225]]

 [[ 0.1903183   0.0367334   0.78393546]]

 [[ 0.40414839  0.54369458  0.224079  ]]]


In [251]:
difference = data_reshaped - data
print(np.shape(difference))
print(difference)

(4, 4, 3)
[[[ 0.          0.          0.        ]
  [ 0.04700741 -0.33212322  0.85535229]
  [ 0.18552338  0.27622178  0.13790907]
  [-0.02830672 -0.2307394   0.69776553]]

 [[-0.04700741  0.33212322 -0.85535229]
  [ 0.          0.          0.        ]
  [ 0.13851597  0.60834501 -0.71744322]
  [-0.07531412  0.10138382 -0.15758676]]

 [[-0.18552338 -0.27622178 -0.13790907]
  [-0.13851597 -0.60834501  0.71744322]
  [ 0.          0.          0.        ]
  [-0.21383009 -0.50696118  0.55985646]]

 [[ 0.02830672  0.2307394  -0.69776553]
  [ 0.07531412 -0.10138382  0.15758676]
  [ 0.21383009  0.50696118 -0.55985646]
  [ 0.          0.          0.        ]]]


In [252]:
distances = np.sum(difference**2, axis=2)
print(np.shape(distances))
print(distances)

(4, 4)
[[ 0.          0.84414306  0.12973631  0.54091867]
 [ 0.84414306  0.          0.90399509  0.04078448]
 [ 0.12973631  0.90399509  0.          0.61617221]
 [ 0.54091867  0.04078448  0.61617221  0.        ]]


In [253]:
distances[np.diag_indices_from(distances)] = np.inf  # supprimer les distances des points à eux-même

In [254]:
np.argmin(distances, axis=1)

array([2, 3, 0, 1])

#### Comparaison des efficacités

In [297]:
def nearset_neighbors_sklear(data):
    from sklearn.neighbors import NearestNeighbors
    nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(data)
    distances, indices = nbrs.kneighbors(data)
    return indices[:, 1]

In [259]:
n_points = 100
n_dims = 3

In [260]:
data = np.random.random((n_points, n_dims))

In [261]:
%timeit nearset_neighbors_sklear(data)

394 µs ± 3.16 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [262]:
%timeit nearset_neighbors(data)

316 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [267]:
n_points = 10000
n_dims = 3

In [268]:
data = np.random.random((n_points, n_dims))

In [269]:
%timeit nearset_neighbors_sklear(data)

44.1 ms ± 199 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [270]:
%timeit nearset_neighbors(data)

3.51 s ± 9.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
